name: iniciofront
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  hexcolor: ^3.0.1
  http: ^1.2.1
  flutter_login: ^5.0.0
  animate_do: ^3.3.4
  assets: ^0.0.1
  animated_text_kit: ^4.2.2
  simple_circular_progress_bar: ^1.0.2
  email_validator: ^2.1.17
  another_flushbar: ^1.12.30
  build: ^2.4.1
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  carousel_slider: ^4.2.1
  provider: ^6.1.2
  dart_jsonwebtoken: ^2.14.0
  url_launcher: ^6.3.0
  google_nav_bar: ^5.0.6
  flutter_local_notifications: ^17.1.2
  fui_kit: ^2.0.2
  flutter_staggered_animations: ^1.1.1
  google_maps_flutter: ^2.7.0
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  flutter_spinbox: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    -  assets/